### ISSUE TITLE
Trying to use with brave brower. Sync page does not work.

### ISSUE THREAD

**Issue by Dubhs** [lasuillard/raindrop-sync-chrome#73]
Is there any cross compatibility with brave? it does support most other extensions i've tried so not sure.
extension page returns this:

Uncaught (in promise) TypeError: Cannot read properties of null (reading '$id')
Context
src/options.html
Stack Trace
assets/options.html-cfacd102.js:6 (anonymous function)

**Comment by lasuillard** [comment]
Thanks for your interest in this extension. Sadly, there's no test that has been made on browsers other than Chrome. I'm planning to add support more browsers in the future, but I can't say when it's coming.

By the way, the error message you provided seems likely to be a problem of the implementation of extension itself rather than the browser API. I'll check it later again.

**Comment by lasuillard** [comment]
Fixed in v0.4.0 (tested with Chrome). If still persist for Brave, please reopen the issue.
