### ISSUE TITLE
Raindrop Sync for Chrome  v0.4.0 - Lack of information in documentation

### ISSUE THREAD

**Issue by drueppela** [lasuillard/raindrop-sync-chrome#75]
@lasuillard: Many thanks for your effort

I installed: Raindrop Sync for Chrome v0.4.0

 I followed step by step the documentation from

https://github.com/lasuillard/raindrop-sync-chrome

I am struggling in section: Initializing the Application

1. done
2. done
3. Create an Integration in Raindrop.io
I did not find a documentation where to get "Site" and "Redirect URL" and "Refresh Token". I tried to make a best guess but nothing is synched:

When I wait, nothing happens.

If I click on
Bookmarks > Bookmarks synchronization settings. > Synchronize
nothing happens.

If I click on
Bookmarks > Bookmarks synchronization settings. > Fetch
I get the result: "<Directory> no-title"

**Comment by lasuillard** [comment]
Thank you for your interest in this extension. As you mentioned, the current documentation is outdated, and I plan to update it when I have some time (but not sure when it would be).

To run the sync process, please follow these steps:

1. Create an integration in Raindrop.io.
2. Generate a test token and enter it in the **Access Token** field. This method is currently preferred over OAuth registration due to its simplicity and ease of use.
3. Choose your **Sync Location** and click the **Save** button.

![image](https://github.com/user-attachments/assets/45af1356-dc85-42d7-9aa8-85479391d48b)

To manually sync, navigate to **Bookmarks** and click **Fetch** first:

![image](https://github.com/user-attachments/assets/5a196055-3e66-4010-a32b-62ddbdd55919)

Then, click the **Synchronize** button to sync your bookmarks:

![image](https://github.com/user-attachments/assets/e9cd5f4c-09e1-4724-886b-5349a4583520)

The current **Bookmarks** tab was originally implemented for debugging purposes and will soon be redesigned for improved usability.

I discovered that the **no-title** result appears due to a bug where bookmarks not assigned to a collection are excluded. This issue is being tracked under issue #77. As a temporary workaround, try syncing with a new collection folder.

**Comment by drueppela** [comment]
@lasuillard : Many thanks.

The connection works but I think that there is only a one-way-sync from RAINDROP.IO to Google Chrome Bookmarks. 

If I save a bookmark in Google Chrome it will be deleted after a while.

I think a rock-solid two-way-sync is needed.

----------------------

I don't understand what is happening when I click on "Fetch" or "Synchronize"

---------------------------

All bookmarks in RAINDROP.IO are doubled in Chrome Bookmarks

**Comment by lasuillard** [comment]
The sync behavior is intentionally one-way (Browser <- Raindrop.io). This extension caters to users who want to use Raindrop.io as a bookmark source but require a local copy in their browser for specific reasons:

- To achieve slightly faster access by utilizing the browser's built-in capabilities, avoiding queries to Raindrop.io bookmarks.
- Because certain tools depend on bookmarks stored in the browser; for instance, I use [Albert](https://github.com/albertlauncher/albert)'s Chromium Plugin.

If you're seeking bidirectional sync, this extension may not meet your needs. Currently, there are no plans to implement bidirectional sync. The official Raindrop extension might be more suitable for that purpose.

---

The **Bookmarks** tab is currently intended for debugging. The **Fetch** button loads the entire dataset, and **Synchronize** performs a sync with the loaded data. If the data hasn't been fetched yet, the sync will not proceed.

---

I have identified the issue of some bookmarks being duplicated and will address it promptly.
